version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: micros
    ports:
      - "5432:5432"

  usuarios:
    build: ./usuarios
    container_name: api_usuarios
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  produtos:
    build: ./produtos
    container_name: api_produtos
    ports:
      - "3001:3000"
    depends_on:
      - postgres
